title: Alicia Teo # your name (or website title) here
logo: <center>"/images/Profile.jpg"</center> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Wharton MBA & MSc in Computer Science
  <br>
  
  <br><br>
  Tech Skills
  <br><br>
  <a href="https://www.linkedin.com/in/alicia-teo/"> LinkedIn</a>
  <br>
  <a href="https://www.linkedin.com/in/alicia-teo/"> Github Repo</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
