title: Alicia Teo # your name (or website title) here
logo: "/images/Profile.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b> About Me </b>
  <br> Hi! I'm Alicia. I'm a graduate student pursuing a dual degree 
  MBA at Wharton and Computer Science at the University of Pennsylvania.
  <br>

  <b> Skills </b>
  <br>
  <b> Front-End: </b> JavaScript, CSS, HTML
  <br>
  <b> Back-End: </b> Java, C
  <br>
  <b> Data Analysis: </b> Python, R

  <br><br>
  <a href="https://www.linkedin.com/in/alicia-teo/"> View my LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
